apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
- ../../../applications/base
- ../../../projects/base

patchesJSON6902:
- target:
    group: argoproj.io
    kind: ApplicationSet
    name: cluster-config
    version: v1alpha1
  patch: |-
    - op: replace
      path: /spec/generators/0/git/directories/0/path
      value: manifests-extra/*
